version: '3.8'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: CatalogApi/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13-management  # includes management UI
    ports:
      - "5672:5672"   # AMQP protocol (used by your C# code)
      - "15672:15672" # Management UI (optional)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: BasketApi/Dockerfile
    ports:
      - "5002:8080"
    networks:
      - backend

networks:
  backend:
   driver: bridge

